global:
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#vyacheslav_egorov'
